### PR TITLE
hyprland v0.49.0 support

### PR DESCRIPTION
**Pull request by alexeytroshkin**
Greetings, I tried to install this plugin today and got build errors:

```bash
[v] parsed commit 9958d297641b5c84dcff93f9039d80a5ad37ab00 at branch  on Thu May 8 20:15:18 2025, commits 6098
✔ Hyprland headers OK
→ Building hyprchroma
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━  3 / 5  Building plugin(s)[v] shell returned:  -> cd /run/user/1000/hyprpm/p47hf1nd3r && PKG_CONFIG_PATH="/var/cache/hyprpm/p47hf1nd3r/headersRoot/share/pkgconfig" make all
mkdir -p out
g++ -shared -fPIC --no-gnu-unique src/*.cpp -Isrc/ -o out/hyprchroma.so -g `pkg-config --cflags pixman-1 libdrm hyprland hyprlang` -std=c++2b -DWLR_USE_UNSTABLE
In file included from src/Helpers.h:8,
                 from src/Helpers.cpp:1:
src/TexturesDark.h:6:10: fatal error: hyprland/src/render/shaders/Textures.hpp: No such file or directory
    6 | #include <hyprland/src/render/shaders/Textures.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from src/Helpers.h:8,
                 from src/WindowInverter.h:6,
                 from src/main.cpp:1:
src/TexturesDark.h:6:10: fatal error: hyprland/src/render/shaders/Textures.hpp: No such file or directory
    6 | #include <hyprland/src/render/shaders/Textures.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from src/Helpers.h:8,
                 from src/WindowInverter.h:6,
                 from src/WindowInverter.cpp:1:
src/TexturesDark.h:6:10: fatal error: hyprland/src/render/shaders/Textures.hpp: No such file or directory
    6 | #include <hyprland/src/render/shaders/Textures.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:7: all] Error 1


✖ Plugin hyprchroma failed to build.
  This likely means that the plugin is either outdated, not yet available for your version, or broken.
  If you are on -git, update first
  Try re-running with -v to see more verbose output.
```

I have made changes that allow me to build the plugin successfully, but there is a problem - after enabling it, I didn't see any change in the appearance of the windows. I couldn't figure out what's wrong because I have no experience in developing C++ and hyprland plugins (and I'm new to Linux), so I'll leave this PR here in the hope that it will help to release support for hyprland v0.49.0 sooner. Thanks in advance

### CODE REVIEW

**Comment by simonkovtyk** [comment]
Bump

**Comment by ayuuuvauuu** [comment]
bump

**Comment by ayuuuvauuu** [comment]
there's an error

output

```
❯ hyprpm add https://github.com/AlexTroshkin/Hyprchroma.git -v
[sudo] password for bro_grammer:
[v] running version returned: Hyprland 0.49.0 built from branch  at commit 9958d297641b5c84dcff93f9039d80a5ad37ab00  (version: bump to 0.49.0).
Date: Thu May 8 22:15:18 2025
Tag: v0.49.0, commits: 6098
built against:
 aquamarine 0.8.0
 hyprlang 0.6.3
 hyprutils 0.7.1
 hyprcursor 0.1.12
 hyprgraphics 0.1.3


no flags were set

[v] parsed commit 9958d297641b5c84dcff93f9039d80a5ad37ab00 at branch  on Thu May 8 22:15:18 2025, commits 6098
✔ adding a new plugin repository from https://github.com/AlexTroshkin/Hyprchroma.git
  MAKE SURE that you trust the authors. DO NOT install random plugins without verifying the code and author.
  Are you sure? [Y/n] y

 ╍━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0 / 5  Cloning the plugin re
→ Cloning https://github.com/AlexTroshkin/Hyprchroma.git
 ╍━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0 / 5  Cloning the plugin re
✔ cloned
 ━━━━━━━━╍━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  1 / 5  Cloning the plugin re
 ━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  1 / 5  Reading the
✔ found hyprpm manifest
 ━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  1 / 5  Reading the
✔ parsed manifest, found 1 plugins:
 ━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2 / 5  Reading the
→ hyprchroma by alexhulbert, micha4w version
 ━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2 / 5  Reading the
→ Manifest has 13 pins, checking
 ━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2 / 5  Reading the
✔ commit pin cf36dd32b0ee9cda949904866d152a7a4c851b53 matched hl, resetting
 ━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2 / 5  Reading the manifest[v] git submodule update --init returned:
 ━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2 / 5  Verifying headers[v] installed version returned: Hyprland 0.49.0 built from branch  at commit 9958d297641b5c84dcff93f9039d80a5ad37ab00  (version: bump to 0.49.0).
Date: Thu May 8 22:15:18 2025
Tag: v0.49.0, commits: 6098
built against:
 aquamarine 0.8.0
 hyprlang 0.6.3
 hyprutils 0.7.1
 hyprcursor 0.1.12
 hyprgraphics 0.1.3


no flags were set


[v] parsed commit 9958d297641b5c84dcff93f9039d80a5ad37ab00 at branch  on Thu May 8 22:15:18 2025, commits 6098
✔ Hyprland headers OK
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━  3 / 5  Verifying he
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━  3 / 5  Building plu
→ Building hyprchroma
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━  3 / 5  Building plugin(s)[v] shell returned:  -> cd /run/user/1000/hyprpm/bro_grammer && PKG_CONFIG_PATH="/var/cache/hyprpm/bro_grammer/headersRoot/share/pkgconfig" make all
mkdir -p out
g++ -shared -fPIC --no-gnu-unique src/*.cpp -Isrc/ -o out/hyprchroma.so -g `pkg-config --cflags pixman-1 libdrm hyprland hyprlang` -std=c++2b -DWLR_USE_UNSTABLE
In file included from /usr/include/hyprland/src/defines.hpp:5,
                 from /usr/include/hyprland/src/render/OpenGL.hpp:3,
                 from src/Helpers.h:6,
                 from src/Helpers.cpp:1:
/usr/include/hyprland/src/helpers/Color.hpp:4:10: fatal error: hyprgraphics/color/Color.hpp: No such file or directory
    4 | #include <hyprgraphics/color/Color.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /usr/include/hyprland/src/defines.hpp:5,
                 from /usr/include/hyprland/src/plugins/PluginSystem.hpp:3,
                 from src/WindowInverter.h:4,
                 from src/WindowInverter.cpp:1:
/usr/include/hyprland/src/helpers/Color.hpp:4:10: fatal error: hyprgraphics/color/Color.hpp: No such file or directory
    4 | #include <hyprgraphics/color/Color.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /usr/include/hyprland/src/defines.hpp:5,
                 from /usr/include/hyprland/src/plugins/PluginSystem.hpp:3,
                 from src/WindowInverter.h:4,
                 from src/main.cpp:1:
/usr/include/hyprland/src/helpers/Color.hpp:4:10: fatal error: hyprgraphics/color/Color.hpp: No such file or directory
    4 | #include <hyprgraphics/color/Color.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:7: all] Error 1


✖ Plugin hyprchroma failed to build.
  This likely means that the plugin is either outdated, not yet available for your version, or broken.
  If you are on -git, update first
  Try re-running with -v to see more verbose output.

 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━  3 / 5  Building plu
✔ all plugins built
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━  3 / 5  Building plu
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━  4 / 5  Installing re
✔ installed repository
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━  4 / 5  Installing re
✔ you can now enable the plugin(s) with hyprpm enable
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━  4 / 5  Installing re
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5 / 5  Done!

```

**Comment by LimoSenpai** [comment]
bump

**Comment by alexhulbert** [comment]
Good news! The `glsl-plugin` branch of this repo, which is going to get merged into hypr-darkwindow soon, works with hyprland version 0.50! The author of the original repo added support for custom shaders.

Once the custom_shaders branch of hypr-darkwindow is merged, you'll be able to just use Hypr-DarkWindow, which is much more actively maintained than my fork!

Here are some relevant links:
[The Hypr-DarkWindow GitHub issue](https://github.com/micha4w/Hypr-DarkWindow/issues/16)
[The changes I made to my hyprland config](https://github.com/alexhulbert/SeaGlass/commit/7a59f084b46de793132a953ace2cd15dac11ede0)
